Fix int overflow exception in unittest
Fixes:

  File ".../versioning/version.py", line 30, in __init__
      if self < 0:
  OverflowError: Python int too large to convert to C long

Don't use __cmp__ which is deprecated and restricted to C
long ints, rather than python's arbitrary precision ints.

Copied from Pádraig Brady's Fedora patch:

http://pkgs.fedoraproject.org/cgit/python-migrate.git/commit/?id=a01bf449

Co-authored-by: Pádraig Brady <pbrady@redhat.com>
Change-Id: I71f349f97507525b2f2edaf034005d67b6cc3987